mode: ContinuousDeployment
branches:
  main:
    regex: ^main$
    increment: Patch
    tag: ''
    prevent-increment-of-merged-branch-version: true
  develop:
    regex: ^develop$
    increment: Minor
    tag: beta
  feature:
    regex: ^features?[/-]
    increment: Minor
    tag: alpha
ignore:
  sha: []
