<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Linbik.Gateway.TokenIssuer</RootNamespace>
    <AssemblyName>linbik-token</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\AspNet\Linbik.Core\Linbik.Core.csproj" />
  </ItemGroup>

</Project>
