using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Linbik.Slices.Generators;

/// <summary>Emits endpoint and service registration code from extracted slice metadata.</summary>
internal static class LinbikSliceEmitter
{
    internal static void Emit(SourceProductionContext spc, ImmutableArray<SliceModel> models, string? assemblyName)
    {
        var valid = new List<SliceModel>();
        foreach (var model in models)
        {
            if (!model.Valid)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    LinbikSliceConstants.MissingRequestOrHandler, model.Location, model.DisplayName));
                continue;
            }
            valid.Add(model);
        }

        // Hiç geçerli slice yoksa registry üretme. Aksi halde slice içermeyen
        // projeler (ör. Linbik.Slices'ın kendisi) boş bir LinbikSlicesRegistry
        // üretip dll'e gömer; bu, gerçek slice'ları olan tüketici projede
        // üretilen registry ile çakışır / onu gölgeler.
        if (valid.Count == 0)
        {
            // Linbik.Slices kütüphanesinin kendisi hiçbir zaman slice içermez;
            // bu beklenen durum için gereksiz bir uyarı üretme.
            if (assemblyName != "Linbik.Slices")
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    LinbikSliceConstants.NoSlicesFound, Location.None, assemblyName ?? "?"));
            }
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {LinbikSliceConstants.GeneratedNamespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Source generator tarafından üretilen slice kayıt ve mapping'leri.</summary>");
        sb.AppendLine("    public static class LinbikSlicesRegistry");
        sb.AppendLine("    {");

        // AddLinbikSlices
        sb.AppendLine("        /// <summary>ILinbikSender + tüm slice handler/validator kayıtlarını ekler.</summary>");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddLinbikSlices(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine("            global::Linbik.Slices.LinbikSlicesServiceCollectionExtensions.AddLinbikSender(services);");
        foreach (var m in valid)
        {
            sb.AppendLine($"            services.AddScoped<global::Linbik.Slices.ILinbikHandler<{m.RequestFqn}, {m.ResponseFqn}>, {m.HandlerFqn}>();");
            if (m.ValidatorFqn is not null)
                sb.AppendLine($"            services.AddScoped<global::Linbik.Slices.ILinbikValidator<{m.RequestFqn}>, {m.ValidatorFqn}>();");
        }
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // MapLinbikSlices
        sb.AppendLine("        /// <summary>Tüm slice endpoint'lerini map'ler (flow metadata + filter dahil).</summary>");
        sb.AppendLine("        public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapLinbikSlices(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
        sb.AppendLine("        {");
        foreach (var m in valid)
        {
            var mapMethod = MapMethodFor(m.Method);
            sb.AppendLine("            {");
            sb.AppendLine($"                var __e = app.{mapMethod}(\"{Escape(m.Pattern)}\",");
            // GET/DELETE/HEAD gövdesiz (çoğu istemci — taray\u0131c\u0131 fetch/XHR dahil —
            // bu metotlara body koymay\u0131 client-side reddeder): [AsParameters] ile
            // Request'in property'leri query string'ten ba\u011flan\u0131r (\u00f6r. ?threadId=..&page=1).
            // POST/PUT/PATCH: [FromBody] ile JSON g\u00f6vdeden okunur (konvansiyon).
            // Request tipleri (t\u00fcm slice'larda) d\u00fcz alanlardan olu\u015ftu\u011fu i\u00e7in
            // [AsParameters] ile tam uyumlu (Guid/string/int?/bool vb.).
            var isBodylessVerb = m.Method is "GET" or "DELETE" or "HEAD";
            var bindingAttr = isBodylessVerb
                ? "[global::Microsoft.AspNetCore.Http.AsParameters]"
                : "[global::Microsoft.AspNetCore.Mvc.FromBody]";
            sb.AppendLine($"                    static ({bindingAttr} {m.RequestFqn} request, global::Linbik.Slices.ILinbikSender sender, global::System.Threading.CancellationToken ct)");
            sb.AppendLine($"                        => global::Linbik.Slices.Endpoints.LinbikEndpoint.Handle<{m.RequestFqn}, {m.ResponseFqn}>(request, sender, ct));");
            if (m.IsAuthorizeFlow)
            {
                // [LAuthorizeFlow]: Linbik-Flow header'ına güvenmek yerine gerçek
                // authentication scheme'ini dener — Gateway olmadan da güvenli.
                sb.AppendLine("                __e.AddEndpointFilter<global::Linbik.Slices.Endpoints.LinbikAuthorizeFlowEndpointFilter>();");
            }
            else
            {
                sb.AppendLine("                __e.AddEndpointFilter<global::Linbik.Slices.Endpoints.LinbikFlowEndpointFilter>();");
            }
            sb.AppendLine($"                __e.WithMetadata(new global::Linbik.Core.Attributes.LFlowAuthorizeAttribute({m.FlowArgs}));");
            sb.AppendLine($"                __e.WithTags(\"{Escape(m.Tag)}\");");
            // OperationId = slice sınıf adı (ör. "CreateComment"). Bu olmadan ASP.NET'in
            // varsayılan operationId üretimi path+method'tan türetilen uzun/okunaksız bir
            // isim kullanır — NSwag gibi istemci üreteçleri operationId'yi metot adı olarak
            // kullanır, bu yüzden temiz metot isimleri (ör. client.CreateCommentAsync()) için şart.
            sb.AppendLine($"                __e.WithName(\"{Escape(m.DisplayName)}\");");
            if (m.Summary is not null)
                sb.AppendLine($"                __e.WithSummary(\"{Escape(m.Summary)}\");");
            if (m.Description is not null)
                sb.AppendLine($"                __e.WithDescription(\"{Escape(m.Description)}\");");
            // LinbikEndpoint.Handle tip-silinmi\u015f Task<IResult> d\u00f6nd\u00fcr\u00fcr; OpenAPI generator'\u0131
            // bundan y\u00fck (response) \u015femas\u0131n\u0131 \u00e7\u0131karamaz (docs'ta yaln\u0131z "200 OK" g\u00f6r\u00fcn\u00fcr,
            // \u015fema yok). .Produces<T>() ile ba\u015far\u0131 + bilinen hata durum kodlar\u0131n\u0131n
            // hepsinin ayn\u0131 LBaseResponse<TResponse> zarf\u0131n\u0131 kulland\u0131\u011f\u0131n\u0131 aç\u0131k\u00e7a bildiriyoruz
            // (LError: 400/403/404/409 — bkz. Linbik.Slices.Results.LError).
            sb.AppendLine($"                __e.Produces<global::Linbik.Core.Responses.LBaseResponse<{m.ResponseFqn}>>(200);");
            sb.AppendLine($"                __e.Produces<global::Linbik.Core.Responses.LBaseResponse<{m.ResponseFqn}>>(400);");
            sb.AppendLine($"                __e.Produces<global::Linbik.Core.Responses.LBaseResponse<{m.ResponseFqn}>>(403);");
            sb.AppendLine($"                __e.Produces<global::Linbik.Core.Responses.LBaseResponse<{m.ResponseFqn}>>(404);");
            sb.AppendLine($"                __e.Produces<global::Linbik.Core.Responses.LBaseResponse<{m.ResponseFqn}>>(409);");
            sb.AppendLine("            }");
        }
        sb.AppendLine("            return app;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("LinbikSlicesRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string MapMethodFor(string method) => method switch
    {
        "GET" => "MapGet",
        "PUT" => "MapPut",
        "DELETE" => "MapDelete",
        "PATCH" => "MapPatch",
        _ => "MapPost",
    };

    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

}
