services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: ../..
      dockerfile: examples/AspNet.Gateway/ApiGateway/Dockerfile


  aggregationservice:
    image: ${DOCKER_REGISTRY-}aggregationservice
    build:
      context: ../..
      dockerfile: examples/AspNet.Gateway/Services/AggregationService/Dockerfile


  arithmeticservice:
    image: ${DOCKER_REGISTRY-}arithmeticservice
    build:
      context: ../..
      dockerfile: examples/AspNet.Gateway/Services/ArithmeticService/Dockerfile


