name: Multi Project NuGet Publish with GitVersion

on:
  push:
    branches:
      - main
      - dev
      # - 'feature/*'
      # - 'release'
  workflow_dispatch:

jobs:
  build-test-pack-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # tam geçmişi çek

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    - name: Install GitVersion
      uses: GitTools/actions/gitversion/setup@v0.9.14
      with:
        versionSpec: '5.x'

    - name: Calculate Version
      id: gitversion
      uses: GitTools/actions/gitversion/execute@v0.9.14
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml

    - name: Restore
      run: dotnet restore ./examples/AspNet/AspNet.sln

    - name: Build
      run: dotnet build ./examples/AspNet/AspNet.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./examples/AspNet/AspNet.sln --no-restore --verbosity normal

    - name: Pack Linbik.Core
      run: dotnet pack ./src/AspNet/Linbik.Core/Linbik.Core.csproj -c Release -o ./nupkg /p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }}

    - name: Pack Linbik.JwtAuthManager (with updated Linbik.Core version)
      run: dotnet pack ./src/AspNet/Linbik.JwtAuthManager/Linbik.JwtAuthManager.csproj -c Release -o ./nupkg /p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }}

    - name: Pack Linbik.YARP (with updated Linbik.Core version)
      run: dotnet pack ./src/AspNet/Linbik.YARP/Linbik.YARP.csproj -c Release -o ./nupkg /p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }}

    - name: Pack Linbik.Server (with updated Linbik.Core version)
      run: dotnet pack ./src/AspNet/Linbik.Server/Linbik.Server.csproj -c Release -o ./nupkg /p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }} 

    - name: Publish all packages
      run: |
        dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
